### ISSUE TITLE
hook "hookDisplayContentWrapperTop" appelée sur chaque liste produits

### ISSUE THREAD

**Issue by mokabiwd** [richemeflo/ModulePrestashopBabolat#2]
Bonjour,

pour des soucis de performances, serait-il possible d'ajouter une vérification dans le hook "hookDisplayContentWrapperTop" vous assurant, qu'avant exécution du code que l'on est bien sur la bonne page ? Actuellement, peu importe la liste produits, le code est exécuté ce qui peut impacter les performances du site. De plus, si une erreur venait à survenir sur le module, cela planterait toutes les listes de produits ce que nous souhaiterions éviter.

**Comment by richemeflo** [comment]
Bonjour,
Merci pour le retour. Effectivement vous avez raison,  je vais essayer de régler ça ce soir !

**Comment by richemeflo** [comment]
J'ai bien modifié ce que vous m'avez demandé (error 500 et verification d'url avant l'execution du code dans le hook).
J'essaye de trouver un hook plus optimal et flexible pour notre cas mais j'ai pas encore trouvé ça dans la doc de prestashop :/

**Comment by mokabiwd** [comment]
@richemeflo , le hook que vous utilisez me semble adéquat. Le but c'est surtout au sein de ce hook de faire quelque chose comme :

```php
public function hookDisplayContentWrapperTop()
{
  if ($currentUrl !== 'mon/url/babolat') {
     // je ne fais rien
     return;
  }
}
```

Aussi, voyez-vous un inconvénient de mettre sur le git, le code source du plugin plutôt que le zip ? Cela serait plus simple pour voir vos correctifs et que nous puissions avancer plus vite. L'idée serait d'avoir comme d'autre module, le code source non offusqué et directement visible via l'interface de github comme [celui-ci](https://github.com/faktiva/prestashop-clean-urls) par exemple.

**Comment by richemeflo** [comment]
Je l’ai push à 2h le zip avec la verif dans le hook.
De base j’avais créé ce github juste pour envoyer le module à des non-dev (le zip étant trop gros pour les mails) d’où le fait que j’ai pas mis le code source dezippé. Je fais ça dès que j’ai mon ordi perso sous la main.

**Comment by mokabiwd** [comment]
Parfait ! Merci @richemeflo ! Je vous ai envoyé un mail pour la suite.
